Repository TeamHARA/KAERA_Android, pull requests merged in 2023-07, with the labels that each got.

#13 Feat/#11 파이어베이스 크래시스틱스 추가
  app/build.gradle
  app/google-services.json
  build.gradle
Labels: ✍FEAT

#12 Feat/#8 고민작성 액티비티 상단 앱바 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/presentation/MainActivity.kt
  app/src/main/java/com/hara/kaera/presentation/util/ViewExtension.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteActivity.kt
  app/src/main/res/drawable/empty_stone.xml
  app/src/main/res/drawable/shape_rect_gray3_8.xml
  app/src/main/res/drawable/shape_rect_gray4_10.xml
  app/src/main/res/drawable/shape_rect_yellow1_10.xml
  app/src/main/res/drawable/shape_rect_yellow2_0.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/layout_gray3_edittext.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🗺UI

#15 Feat/#14 템플릿 선택 바텀시트 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/presentation/base/BindingDraggableBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/base/BindingNotDraggableBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/util/BindingConversion.kt
  app/src/main/java/com/hara/kaera/presentation/util/GlobalDiffCallBack.kt
  app/src/main/java/com/hara/kaera/presentation/util/LastItemMarginDecoration.kt
  app/src/main/java/com/hara/kaera/presentation/util/OnSingleClickListener.kt
  app/src/main/java/com/hara/kaera/presentation/util/ViewExtension.kt
  app/src/main/java/com/hara/kaera/presentation/write/TemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/write/adapter/TemplateChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/write/data/DummyTemplateData.kt
  app/src/main/java/com/hara/kaera/presentation/write/data/TemplateData.kt
  app/src/main/res/drawable/gem_blue_s_off.png
  app/src/main/res/drawable/gem_blue_s_on.png
  app/src/main/res/drawable/shape_rect_gray1_16.xml
  app/src/main/res/drawable/shape_rect_gray1_stroke_gray5_8.xml
  app/src/main/res/drawable/shape_rect_gray1_stroke_yellow1_8.xml
  app/src/main/res/drawable/shape_rect_grayline_12.xml
  app/src/main/res/layout/bottomsheet_template_choice.xml
  app/src/main/res/layout/item_template.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: 🗺UI, ✍FEAT

#19 Feat/#18 고민작성 템플릿 교체 및 버튼 활성화 로직
  app/src/main/java/com/hara/kaera/presentation/write/TemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/write/adapter/TemplateChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/write/data/TemplateDetailData.kt
  app/src/main/res/drawable/selector_rect_gray4_yellow1_10.xml
  app/src/main/res/drawable/selector_text_white_black.xml
  app/src/main/res/drawable/shape_rect_gray1_gray3_8.xml
  app/src/main/res/drawable/shape_rect_gray3_0.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/layout_free_flow_template.xml
  app/src/main/res/layout/layout_gray3_edittext.xml
  app/src/main/res/layout/layout_template.xml
  app/src/main/res/layout/layout_template_empty.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🗺UI, ✍FEAT

#22 feat/#20
  app/src/main/res/drawable/shape_rect_gradient_8.xml
  app/src/main/res/drawable/shape_rect_gray2_10.xml
  app/src/main/res/layout/fragment_temp_storage.xml
  app/src/main/res/layout/item_storage_grid.xml
  app/src/main/res/layout/layout_divider_both.xml
  app/src/main/res/layout/layout_divider_end.xml
  app/src/main/res/layout/layout_divider_start.xml
  app/src/main/res/values/strings.xml
Labels: 🗺UI, ✍FEAT
