Repository TeamHARA/KAERA_Android, pull requests merged in 2023-09, with the labels that each got.

#54 Feat/#53 고민작성 디자인 변경 및 버그 수정
  app/src/main/java/com/hara/kaera/presentation/base/BindingDialogFragment.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/presentation/write/custom/DialogWriteComplete.kt
  app/src/main/java/com/hara/kaera/presentation/write/viewmodel/WriteViewModel.kt
  app/src/main/res/anim/anim_dialog_fade_in.xml
  app/src/main/res/anim/anim_dialog_fade_out.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/layout_free_note_template.xml
  app/src/main/res/layout/layout_template.xml
  app/src/main/res/layout/snackbar_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ⚠FIX, ♻️REFACTOR

#51 Refactor/#49 홈 화면 UI 리팩토링
  app/build.gradle.kts
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSourceImpl.kt
  app/src/main/java/com/hara/kaera/data/mapper/Mapper.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/domain/entity/HomeWorryListEntity.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetHomeWorryListUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetHomeWorryListUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/presentation/MainActivity.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeFragment.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeFragmentStateAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeJewelFragment.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeStoneFragment.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/home/adapter/HomeJewelAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/home/adapter/HomeStoneAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/home/model/Gem.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageTemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/util/BindingConversion.kt
  app/src/main/java/com/hara/kaera/presentation/util/GridRvItemIntervalDecoration.kt
  app/src/main/java/com/hara/kaera/presentation/util/UiState.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/presentation/write/custom/TemplateChoiceBottomSheet.kt
  app/src/main/res/drawable/empty_jewel.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_jewel.xml
  app/src/main/res/layout/fragment_home_stone.xml
  app/src/main/res/layout/item_home_gem.xml
Labels: ♻️REFACTOR

#55 Feat/#50 고민 해결 상세 페이지 UI 및 서버 통신
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/data/datasource/KaeraApi.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSource.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSourceImpl.kt
  app/src/main/java/com/hara/kaera/data/dto/WorryDetailDTO.kt
  app/src/main/java/com/hara/kaera/data/mapper/Mapper.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/di/UseCaseModule.kt
  app/src/main/java/com/hara/kaera/domain/entity/WorryByTemplateEntity.kt
  app/src/main/java/com/hara/kaera/domain/entity/WorryDetailEntity.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetWorryByTemplateUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetWorryByTemplateUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetWorryDetailUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetWorryDetailUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/presentation/detail/DetailAfterActivity.kt
  app/src/main/java/com/hara/kaera/presentation/detail/DetailAfterViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageFragment.kt
  app/src/main/java/com/hara/kaera/presentation/storage/adapter/StorageGridAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/storage/viewmodel/StorageViewModel.kt
  app/src/main/res/drawable/shape_rect_gray1_stroke_gray3_8.xml
  app/src/main/res/layout/activity_detail_after.xml
  app/src/main/res/layout/item_storage_grid.xml
  app/src/main/res/layout/layout_detail_answer.xml
  app/src/main/res/layout/layout_divider_end.xml
  app/src/main/res/layout/layout_divider_start.xml
  app/src/main/res/values/strings.xml
Labels: ✍FEAT

#60 Feat/#56 고민 상세 페이지 - 해결 후 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/data/datasource/KaeraApi.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSource.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSourceImpl.kt
  app/src/main/java/com/hara/kaera/data/dto/DeleteWorryDTO.kt
  app/src/main/java/com/hara/kaera/data/dto/ReviewReqDTO.kt
  app/src/main/java/com/hara/kaera/data/dto/ReviewResDTO.kt
  app/src/main/java/com/hara/kaera/data/mapper/Mapper.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/di/UseCaseModule.kt
  app/src/main/java/com/hara/kaera/domain/entity/DeleteWorryEntity.kt
  app/src/main/java/com/hara/kaera/domain/entity/ReviewResEntity.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/DeleteWorryUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/DeleteWorryUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/domain/usecase/PutReviewUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/PutReviewUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/presentation/detail/DetailAfterActivity.kt
  app/src/main/java/com/hara/kaera/presentation/detail/DetailAfterViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/detail/custom/DialogDeleteWarning.kt
  app/src/main/java/com/hara/kaera/presentation/dialog/DialogWriteSuccess.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageFragment.kt
  app/src/main/java/com/hara/kaera/presentation/storage/viewmodel/StorageViewModel.kt
  app/src/main/res/layout/activity_detail_after.xml
  app/src/main/res/layout/dialog_fragment_write_success.xml
  app/src/main/res/layout/dialog_worry_delete.xml
  app/src/main/res/layout/layout_detail_answer.xml
  app/src/main/res/values/strings.xml
Labels: ✍FEAT

#61 Feat/#59 파이어베이스메세징 수신 클래스 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/application/FirebaseMessaginService.kt
  app/src/main/java/com/hara/kaera/application/Notification.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: ✍FEAT
