Repository TeamHARA/KAERA_Android, pull requests merged in 2023-08, with the labels that each got.

#31 Feat/#30 BuildGradle 파일 KotlinDSL로 마이그레이션
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/build.gradle.kts
  app/proguard-rules.pro
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Versions.kt
  settings.gradle.kts
Labels: ♻️REFACTOR

#26 Feat/#25 Flow 적용 및 의존성 주입
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/application/Application.kt
  app/src/main/java/com/hara/kaera/application/Constant.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraApi.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSource.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSourceImpl.kt
  app/src/main/java/com/hara/kaera/data/dto/TemplateDetailDTO.kt
  app/src/main/java/com/hara/kaera/data/dto/TemplateTypeDTO.kt
  app/src/main/java/com/hara/kaera/data/mapper/Mapper.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/di/DataSourceModule.kt
  app/src/main/java/com/hara/kaera/di/RepositoryModule.kt
  app/src/main/java/com/hara/kaera/di/ServiceModule.kt
  app/src/main/java/com/hara/kaera/di/UseCaseModule.kt
  app/src/main/java/com/hara/kaera/domain/entity/TemplateDetailEntity.kt
  app/src/main/java/com/hara/kaera/domain/entity/TemplateTypesEntity.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetTemplateDetailUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetTemplateDetailUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetTemplateTypeUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetTemplateTypeUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/presentation/util/UiState.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/presentation/write/viewmodel/TestViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/write/viewmodel/WriteViewModel.kt
Labels: ✍FEAT

#38 Feat/#37 고민작성 서버 연결 및 비지니스로직 완성
  app/build.gradle.kts
  app/src/main/java/com/hara/kaera/presentation/util/BindingConversion.kt
  app/src/main/java/com/hara/kaera/presentation/util/UiState.kt
  app/src/main/java/com/hara/kaera/presentation/util/ViewExtension.kt
  app/src/main/java/com/hara/kaera/presentation/write/TemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/presentation/write/adapter/TemplateBottomSheetChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/write/custom/DialogSaveWarning.kt
  app/src/main/java/com/hara/kaera/presentation/write/custom/TemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/write/custom/WriteCompleteDialog.kt
  app/src/main/java/com/hara/kaera/presentation/write/viewmodel/TemplateChoiceViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/write/viewmodel/TestViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/write/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/bottomsheet_template_choice.xml
  app/src/main/res/layout/item_template.xml
  app/src/main/res/layout/layout_free_flow_template.xml
  app/src/main/res/layout/layout_template.xml
  app/src/main/res/values/themes.xml
Labels: ✍FEAT

#34 Feat/#23
  app/src/main/java/com/hara/kaera/presentation/MainActivity.kt
  app/src/main/java/com/hara/kaera/presentation/TempStorageFragment.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageFragment.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageTemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/storage/adapter/StorageGridAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/storage/adapter/StorageTemplateChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/storage/data/DummyStorageData.kt
  app/src/main/java/com/hara/kaera/presentation/storage/data/DummyStorageTemplateData.kt
  app/src/main/java/com/hara/kaera/presentation/storage/data/StorageData.kt
  app/src/main/java/com/hara/kaera/presentation/write/data/DummyTemplateData.kt
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/item_storage_grid.xml
  app/src/main/res/layout/layout_jewel_empty.xml
  app/src/main/res/values/strings.xml
Labels: 🗺UI, ✍FEAT

#36 Feat/#32 커스텀 스낵바
  app/src/main/java/com/hara/kaera/presentation/custom/snackbar/KaeraSnackBar.kt
  app/src/main/res/drawable/shape_rect_gray2_4.xml
  app/src/main/res/layout/snackbar_layout.xml
  app/src/main/res/values/strings.xml
Labels: ✍FEAT

#42 Feat/#24 고민 해결 전 상세 페이지 UI 구성
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/presentation/DetailBeforeActivity.kt
  app/src/main/res/drawable/background_gradient.xml
  app/src/main/res/layout/activity_detail_before.xml
  app/src/main/res/layout/layout_detail_answer.xml
  app/src/main/res/values/themes.xml
Labels: 🗺UI

#48 Feat/#40 홈 화면 서버 통신
  app/src/main/java/com/hara/kaera/data/datasource/KaeraApi.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSource.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSourceImpl.kt
  app/src/main/java/com/hara/kaera/data/dto/HomeWorryListDTO.kt
  app/src/main/java/com/hara/kaera/data/mapper/Mapper.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/di/UseCaseModule.kt
  app/src/main/java/com/hara/kaera/domain/entity/HomeWorryListEntity.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetHomeWorryListUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetHomeWorryListUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeFragment.kt
  app/src/main/java/com/hara/kaera/presentation/home/HomeViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/storage/adapter/StorageTemplateChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/util/BindingConversion.kt
  app/src/main/java/com/hara/kaera/presentation/util/Constant.kt
  app/src/main/java/com/hara/kaera/presentation/write/adapter/TemplateChoiceAdapter.kt
  app/src/main/res/layout/layout_home_gem_item.xml
Labels: ✍FEAT

#43 Feat/#41
  app/src/main/java/com/hara/kaera/presentation/dialog/DialogCompleteFragment.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/presentation/write/adapter/TemplateChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/write/custom/DialogWriteComplete.kt
  app/src/main/java/com/hara/kaera/presentation/write/custom/WriteCompleteDialog.kt
  app/src/main/java/com/hara/kaera/presentation/write/data/DummyTemplateData.kt
  app/src/main/java/com/hara/kaera/presentation/write/data/TemplateDetailData.kt
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/dialog_fragment_wirte_complete.xml
  app/src/main/res/layout/dialog_fragment_worry_mining.xml
  app/src/main/res/layout/layout_free_note_template.xml
  app/src/main/res/layout/layout_template.xml
  app/src/main/res/layout/layout_template_empty.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ✍FEAT

#44 Feat/#39 보관함 서버 통신 및 비즈니스 로직 적용
  app/src/main/java/com/hara/kaera/data/datasource/KaeraApi.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSource.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSourceImpl.kt
  app/src/main/java/com/hara/kaera/data/dto/WorryByTemplateDTO.kt
  app/src/main/java/com/hara/kaera/data/mapper/Mapper.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/di/UseCaseModule.kt
  app/src/main/java/com/hara/kaera/domain/entity/WorryByTemplateEntity.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetWorryByTemplateUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetWorryByTemplateUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageFragment.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageTemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/storage/adapter/StorageGridAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/storage/adapter/StorageTemplateChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/storage/data/DummyStorageData.kt
  app/src/main/java/com/hara/kaera/presentation/storage/data/DummyStorageTemplateData.kt
  app/src/main/java/com/hara/kaera/presentation/storage/data/StorageData.kt
  app/src/main/java/com/hara/kaera/presentation/storage/viewmodel/StorageTemplateChoiceViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/storage/viewmodel/StorageViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/write/adapter/TemplateChoiceAdapter.kt
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/item_storage_grid.xml
  app/src/main/res/values/strings.xml
Labels: ✍FEAT

#52 Feat/#46 익셉션 처리 및 에러에 따른 뷰 변화 로직 구현
  app/src/main/java/com/hara/kaera/core/ApiResult.kt
  app/src/main/java/com/hara/kaera/core/ErrorCodes.kt
  app/src/main/java/com/hara/kaera/core/ErrorType.kt
  app/src/main/java/com/hara/kaera/data/datasource/KaeraDataSourceImpl.kt
  app/src/main/java/com/hara/kaera/data/mapper/Mapper.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/data/util/ErrorHandlerImpl.kt
  app/src/main/java/com/hara/kaera/data/util/SafeFlow.kt
  app/src/main/java/com/hara/kaera/di/ServiceModule.kt
  app/src/main/java/com/hara/kaera/domain/entity/TemplateDetailEntity.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetTemplateDetailUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetTemplateDetailUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetTemplateTypeUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetTemplateTypeUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/domain/util/ErrorHandler.kt
  app/src/main/java/com/hara/kaera/presentation/storage/StorageTemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/storage/adapter/StorageTemplateChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/presentation/storage/viewmodel/StorageTemplateChoiceViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/storage/worrytemplate/WorryTemplateViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/util/Extension.kt
  app/src/main/java/com/hara/kaera/presentation/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/presentation/write/custom/TemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/presentation/write/viewmodel/TemplateChoiceViewModel.kt
  app/src/main/java/com/hara/kaera/presentation/write/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/layout_free_note_template.xml
  app/src/main/res/layout/layout_template.xml
Labels: ✍FEAT
