Repository TeamHARA/KAERA_Android, pull requests merged in 2023-12, with the labels that each got.

#91 Feat/#88 고민 템플릿 화면 QA 이슈 해결
  app/src/main/java/com/hara/kaera/feature/storage/worrytemplate/WorryTemplateActivity.kt
  app/src/main/java/com/hara/kaera/feature/storage/worrytemplate/WorryTemplateAdapter.kt
  app/src/main/java/com/hara/kaera/feature/write/WriteActivity.kt
  app/src/main/res/drawable/instagram_gems.png
  app/src/main/res/layout/activity_worry_template.xml
  app/src/main/res/layout/item_worry_template.xml
  app/src/main/res/layout/layout_worry_template_banner.xml
  app/src/main/res/values/strings.xml
Labels: ⚠FIX

#94 Fix/#93 고민 목록 조회 API 수정된 부분 반영
  app/src/main/java/com/hara/kaera/data/datasource/remote/KaeraApi.kt
  app/src/main/java/com/hara/kaera/data/datasource/remote/KaeraDataSource.kt
  app/src/main/java/com/hara/kaera/data/datasource/remote/KaeraDataSourceImpl.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetHomeWorryListUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/GetHomeWorryListUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/feature/home/HomeViewModel.kt
Labels: ⚠FIX

#98 Feat/#97 토큰 재설정 관련 인터셉터 추가
  app/src/main/java/com/hara/kaera/data/util/BaseInterceptor.kt
  app/src/main/java/com/hara/kaera/data/util/SafeFlow.kt
  app/src/main/java/com/hara/kaera/di/ServiceModule.kt
Labels: ⚠FIX

#104 Feat/#103 12-06 QA 사항반영
  app/src/main/java/com/hara/kaera/feature/detail/DetailBeforeActivity.kt
  app/src/main/java/com/hara/kaera/feature/home/HomeViewModel.kt
  app/src/main/java/com/hara/kaera/feature/storage/StorageFragment.kt
  app/src/main/java/com/hara/kaera/feature/util/Constant.kt
  app/src/main/res/layout/fragment_storage.xml
Labels: ⚠FIX

#108 Feat/#107 홈 리싸이클러뷰 관련 처리 / 마이페이지 스크롤화 / 화면전환 애니메이션 적용
  app/src/main/java/com/hara/kaera/feature/base/BindingActivity.kt
  app/src/main/java/com/hara/kaera/feature/home/HomeFragment.kt
  app/src/main/java/com/hara/kaera/feature/home/adapter/HomeJewelAdapter.kt
  app/src/main/java/com/hara/kaera/feature/home/adapter/HomeStoneAdapter.kt
  app/src/main/java/com/hara/kaera/feature/home/gems/HomeFragmentStateAdapter.kt
  app/src/main/java/com/hara/kaera/feature/util/Constant.kt
  app/src/main/res/anim/anim_none.xml
  app/src/main/res/anim/animation_slide_from_left.xml
  app/src/main/res/anim/animation_slide_to_left.xml
  app/src/main/res/layout/activity_mypage.xml
Labels: ⚠FIX

#113 Fix/#102 고민 보석함 삭제 등 보관함 관련 이슈 해결
  app/src/main/java/com/hara/kaera/feature/mypage/MypageActivity.kt
  app/src/main/java/com/hara/kaera/feature/storage/StorageFragment.kt
  app/src/main/java/com/hara/kaera/feature/storage/worrytemplate/WorryTemplateAdapter.kt
  app/src/main/res/drawable/shape_rect_gradient_10_stroke_gray3_1.xml
  app/src/main/res/drawable/template_banner_image.png
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/item_worry_template.xml
  app/src/main/res/layout/layout_worry_template_banner.xml
  app/src/main/res/values/strings.xml
Labels: ⚠FIX

#117 Feat/#116 로그인 API 수정 및 마이페이지 리팩토링
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/application/Application.kt
  app/src/main/java/com/hara/kaera/application/Constant.kt
  app/src/main/java/com/hara/kaera/application/FirebaseMessaginService.kt
  app/src/main/java/com/hara/kaera/domain/dto/KaKaoLoginReqDTO.kt
  app/src/main/java/com/hara/kaera/feature/login/LoginActivity.kt
  app/src/main/java/com/hara/kaera/feature/login/LoginViewModel.kt
  app/src/main/java/com/hara/kaera/feature/mypage/MypageActivity.kt
  app/src/main/java/com/hara/kaera/feature/splash/StartActivity.kt
  app/src/main/java/com/hara/kaera/feature/splash/StartViewModel.kt
  app/src/main/res/layout/activity_mypage.xml
  app/src/main/res/layout/dialog_fragment_edit.xml
  app/src/main/res/layout/layout_mypage_tab.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: ✍FEAT

#114 Feat/#111 작성화면 guideline 처리 / 버튼 디바운스 / 터치 타겟 증가 / 리플효과 적용
  app/src/main/java/com/hara/kaera/feature/detail/DetailAfterActivity.kt
  app/src/main/java/com/hara/kaera/feature/detail/DetailBeforeActivity.kt
  app/src/main/java/com/hara/kaera/feature/detail/custom/DialogUpdateWarning.kt
  app/src/main/java/com/hara/kaera/feature/dialog/DialogEditFragment.kt
  app/src/main/java/com/hara/kaera/feature/dialog/DialogMineFragment.kt
  app/src/main/java/com/hara/kaera/feature/mypage/MypageActivity.kt
  app/src/main/java/com/hara/kaera/feature/storage/StorageFragment.kt
  app/src/main/java/com/hara/kaera/feature/storage/adapter/StorageTemplateChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/feature/storage/worrytemplate/WorryTemplateActivity.kt
  app/src/main/java/com/hara/kaera/feature/util/BindingConversion.kt
  app/src/main/java/com/hara/kaera/feature/util/ViewExtension.kt
  app/src/main/java/com/hara/kaera/feature/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/feature/write/adapter/TemplateBottomSheetChoiceAdapter.kt
  app/src/main/java/com/hara/kaera/feature/write/custom/TemplateChoiceBottomSheet.kt
  app/src/main/java/com/hara/kaera/feature/write/viewmodel/WriteViewModel.kt
  app/src/main/res/drawable/image_ripple_effect.xml
  app/src/main/res/drawable/ripple_rect_gradient_8.xml
  app/src/main/res/drawable/ripple_rect_gray1_stroke_gray4_30.xml
  app/src/main/res/drawable/ripple_rect_gray1_stroke_gray5_8.xml
  app/src/main/res/drawable/ripple_rect_gray1_stroke_yellow1_8.xml
  app/src/main/res/drawable/ripple_rect_gray2_10.xml
  app/src/main/res/drawable/ripple_rect_gray2_8.xml
  app/src/main/res/drawable/ripple_rect_gray3_8.xml
  app/src/main/res/drawable/ripple_rect_gray4_10.xml
  app/src/main/res/drawable/ripple_rect_gray4_yellow1_8.xml
  app/src/main/res/drawable/ripple_rect_gray5_12.xml
  app/src/main/res/drawable/ripple_rect_gray5_8.xml
  app/src/main/res/drawable/ripple_rect_yellow1_10.xml
  app/src/main/res/drawable/ripple_rect_yellow1_12.xml
  app/src/main/res/layout/activity_detail_after.xml
  app/src/main/res/layout/activity_detail_before.xml
  app/src/main/res/layout/activity_mypage.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_worry_template.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/dialog_fragment_backpress_warning.xml
  app/src/main/res/layout/dialog_fragment_deadline.xml
  app/src/main/res/layout/dialog_fragment_edit.xml
  app/src/main/res/layout/dialog_fragment_fullstone.xml
  app/src/main/res/layout/dialog_fragment_restart.xml
  app/src/main/res/layout/dialog_fragment_templatechange_warning.xml
  app/src/main/res/layout/dialog_fragment_worry_mining.xml
  app/src/main/res/layout/dialog_mypage.xml
  app/src/main/res/layout/dialog_worry_delete.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_storage.xml
  app/src/main/res/layout/item_storage_grid.xml
  app/src/main/res/layout/item_template.xml
  app/src/main/res/layout/item_worry_template.xml
  app/src/main/res/layout/layout_error_network.xml
  app/src/main/res/layout/layout_jewel_empty.xml
Labels: ✍FEAT

#121 Feat/#75 글 작성/수정/삭제, 데드라인 수정 flow 변경
  app/src/main/java/com/hara/kaera/data/dto/EditDeadlineResDTO.kt
  app/src/main/java/com/hara/kaera/data/dto/WorryDetailDTO.kt
  app/src/main/java/com/hara/kaera/data/dto/WriteWorryResDTO.kt
  app/src/main/java/com/hara/kaera/data/mapper/Mapper.kt
  app/src/main/java/com/hara/kaera/data/repository/KaeraRepositoryImpl.kt
  app/src/main/java/com/hara/kaera/domain/entity/EditDeadlineEntity.kt
  app/src/main/java/com/hara/kaera/domain/entity/WorryDetailEntity.kt
  app/src/main/java/com/hara/kaera/domain/repository/KaeraRepository.kt
  app/src/main/java/com/hara/kaera/domain/usecase/EditDeadlineUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/EditDeadlineUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/domain/usecase/WriteWorryUseCase.kt
  app/src/main/java/com/hara/kaera/domain/usecase/WriteWorryUseCaseImpl.kt
  app/src/main/java/com/hara/kaera/feature/MainActivity.kt
  app/src/main/java/com/hara/kaera/feature/detail/DetailBeforeActivity.kt
  app/src/main/java/com/hara/kaera/feature/detail/DetailBeforeViewModel.kt
  app/src/main/java/com/hara/kaera/feature/home/HomeFragment.kt
  app/src/main/java/com/hara/kaera/feature/home/HomeViewModel.kt
  app/src/main/java/com/hara/kaera/feature/home/adapter/HomeStoneAdapter.kt
  app/src/main/java/com/hara/kaera/feature/home/gems/HomeFragmentStateAdapter.kt
  app/src/main/java/com/hara/kaera/feature/home/gems/HomeStoneFragment.kt
  app/src/main/java/com/hara/kaera/feature/util/Constant.kt
  app/src/main/java/com/hara/kaera/feature/write/WriteActivity.kt
  app/src/main/java/com/hara/kaera/feature/write/custom/DialogWriteComplete.kt
  app/src/main/java/com/hara/kaera/feature/write/viewmodel/WriteViewModel.kt
  app/src/main/res/layout/activity_detail_after.xml
  app/src/main/res/layout/activity_detail_before.xml
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/dialog_fragment_deadline.xml
  app/src/main/res/layout/dialog_fragment_worry_mining.xml
  app/src/main/res/layout/layout_free_note_template.xml
  app/src/main/res/layout/layout_template.xml
  app/src/main/res/values/strings.xml
Labels: 🗺UI, ✍FEAT, ⚠FIX

#115 Feat/#112 고민캐기 이후 플로우 구현 / 12개 고민 제한 다이얼로그 추가
  app/src/main/java/com/hara/kaera/feature/MainActivity.kt
  app/src/main/java/com/hara/kaera/feature/detail/DetailAfterActivity.kt
  app/src/main/java/com/hara/kaera/feature/detail/DetailBeforeActivity.kt
  app/src/main/java/com/hara/kaera/feature/detail/DetailBeforeViewModel.kt
  app/src/main/java/com/hara/kaera/feature/dialog/DialogSayingFragment.kt
  app/src/main/java/com/hara/kaera/feature/home/HomeFragment.kt
  app/src/main/java/com/hara/kaera/feature/home/HomeViewModel.kt
  app/src/main/java/com/hara/kaera/feature/home/gems/HomeJewelFragment.kt
  app/src/main/java/com/hara/kaera/feature/home/gems/HomeStoneFragment.kt
  app/src/main/java/com/hara/kaera/feature/storage/StorageFragment.kt
  app/src/main/java/com/hara/kaera/feature/util/Constant.kt
  app/src/main/java/com/hara/kaera/feature/util/GridRvItemIntervalDecoration.kt
  app/src/main/java/com/hara/kaera/feature/write/viewmodel/WriteViewModel.kt
  app/src/main/res/drawable-hdpi/gem_green_l.png
  app/src/main/res/drawable-hdpi/gem_green_m.png
  app/src/main/res/drawable-hdpi/gem_green_s_off.png
  app/src/main/res/drawable-hdpi/gem_green_s_on.png
  app/src/main/res/drawable-hdpi/template_banner_image.png
  app/src/main/res/drawable-mdpi/gem_green_l.png
  app/src/main/res/drawable-mdpi/gem_green_m.png
  app/src/main/res/drawable-mdpi/gem_green_s_off.png
  app/src/main/res/drawable-mdpi/gem_green_s_on.png
  app/src/main/res/drawable-mdpi/template_banner_image.png
  app/src/main/res/drawable-xhdpi/gem_green_l.png
  app/src/main/res/drawable-xhdpi/gem_green_m.png
  app/src/main/res/drawable-xhdpi/gem_green_s_off.png
  app/src/main/res/drawable-xhdpi/gem_green_s_on.png
  app/src/main/res/drawable-xhdpi/template_banner_image.png
  app/src/main/res/drawable-xxhdpi/gem_green_l.png
  app/src/main/res/drawable-xxhdpi/gem_green_m.png
  app/src/main/res/drawable-xxhdpi/gem_green_s_off.png
  app/src/main/res/drawable-xxhdpi/gem_green_s_on.png
  app/src/main/res/drawable-xxhdpi/template_banner_image.png
  app/src/main/res/drawable-xxxhdpi/gem_green_l.png
  app/src/main/res/drawable-xxxhdpi/gem_green_m.png
  app/src/main/res/drawable-xxxhdpi/gem_green_s_off.png
  app/src/main/res/drawable-xxxhdpi/gem_green_s_on.png
  app/src/main/res/drawable-xxxhdpi/template_banner_image.png
  app/src/main/res/drawable/instagram_gems.png
  app/src/main/res/drawable/template_banner_image.png
  app/src/main/res/layout/activity_write.xml
  app/src/main/res/layout/dialog_fragment_saying.xml
  app/src/main/res/layout/fragment_home.xml
Labels: ⚠FIX

#119 Feat/#118 알림권한 플로우 수정 / manifest exported 속성 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hara/kaera/application/Notification.kt
  app/src/main/java/com/hara/kaera/feature/MainActivity.kt
  app/src/main/java/com/hara/kaera/feature/mypage/MypageActivity.kt
  app/src/main/java/com/hara/kaera/feature/splash/StartViewModel.kt
  app/src/main/res/layout/activity_mypage.xml
  app/src/main/res/values/strings.xml
Labels: ⚠FIX
